with-expecter: true
dir: "mocks/{{.PackageName}}"
filename: "{{ .InterfaceName | snakecase | firstLower }}.go"
outpkg: "mock_{{.PackageName}}"
packages:
  github.com/babelcoder-enterprise-courses/go-fiber-testing/demo:
    interfaces:
      Repository:
  github.com/babelcoder-enterprise-courses/go-fiber-testing/service:
    config:
      all: true
  github.com/babelcoder-enterprise-courses/go-fiber-testing/repository:
    config:
      all: true